services:
  db:
    image: postgres:16-alpine
    container_name: wedding_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wedding_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    container_name: wedding_website_dev
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DATABASE_URL_TWO: postgresql://postgres:postgres@db:5432/wedding_db
      DATABASE_URL: Host=db;Port=5432;Database=wedding_db;Username=postgres;Password=postgres
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
